### ISSUE TITLE
Documentation: Persistance & docker-compose

### ISSUE THREAD

**Issue by praul** [mtlynch/mediagoblin-docker#50]
Hi there and thanks for the docker image. Attempting to run a persistent media-goblin service, I found that I had to make the following adjustments, and I wanted to share them:

There are some things to be done:
- Remove `$mediadir/media/public/public`  before container start. If this symlink exists, the container will throw an error on startup
- mount-bind mediagoblin.db
- mount-bind datadir
- if you want, mount-bind mediagoblin_local.ini

I created a gist for this: https://gist.github.com/praul/77bdee81a6bb16b609954879e96ec8cd

It works with this docker-compose.yml and this startup script. You have to have the same paths in docker-compose and startup.sh. It is somewhat of a workaround with this script, but I wanted to leave the image untouched.

Note: For some reason, the user activation link is not shown anymore in logs. You have to login with admin:admin and edit/approve users there.

**startup.sh**:
```bash
#!/bin/bash
mediadir=/docker/user/datas/mediagoblin/media
dbdir=/docker/user/datas/mediagoblin/db

docker-compose down --remove-orphans
mkdir "$mediadir" && chmod 777 "$mediadir"
rm "$mediadir/media/public/public"
touch "$dbdir/mediagoblin.db" && chmod 777 "$dbdir/mediagoblin.db"
docker-compose up -d
```

**docker-compose.yml**
```yaml
version: "3"
services:
  mediagoblin:
    image: mtlynch/mediagoblin
    
    ports: 
      - 6543:6543
    volumes:
      - /docker/user/datas/mediagoblin/media:/var/lib/mediagoblin #Your Media Path. Adjust Path in start.sh accordingly
      - /docker/user/datas/mediagoblin/db/mediagoblin.db:/srv/mediagoblin.example.org/mediagoblin/mediagoblin.db  #Your Database Path. Adjust Path in start.sh accordingly
      - ./mediagoblin_local.ini:/srv/mediagoblin.example.org/mediagoblin/mediagoblin_local.ini
    restart: unless-stopped
```

**mediagoblin_local.ini** (untouched)
```ini
# If you want to make changes to this file, first copy it to
# mediagoblin_local.ini, then make the changes there.
#
# If you don't see what you need here, have a look at mediagoblin/config_spec.ini
# It defines types and defaults so it's a good place to look for documentation
# or to find hidden options that we didn't tell you about. :)

# To change the directory you should make sure you change the
# directory in paste.ini and/or your webserver configuration.
#
# [DEFAULT]
# data_basedir = "/var/lib/mediagoblin"

[mediagoblin]
direct_remote_path = /mgoblin_static/
email_sender_address = "notice@mediagoblin.example.org"

## Uncomment and change to your DB's appropiate setting.
## Default is a local sqlite db "mediagoblin.db".
## Don't forget to run `./bin/gmg dbupdate` after having changed it.
# sql_engine = postgresql:///mediagoblin

# Set to false to enable sending notices
email_debug_mode = true

# Set to false to disable registrations
allow_registration = true

# Set to false to disable the ability for users to report offensive content
allow_reporting = true

## Uncomment this to put some user-overriding templates here
# local_templates = %(data_basedir)s/templates/

## You can set your theme by specifying this (not specifying it will
## use the default theme).  Run `gmg assetlink` to apply the change.
## The airy and sandyseventiesspeedboat theme comes with GMG; please
## see the theming docs on how to install other themes.
# theme = airy

## If you want the terms of service displayed, you can uncomment this
# show_tos = true

user_privilege_scheme = "uploader,commenter,reporter"
[storage:queuestore]
base_dir = %(data_basedir)s/media/queue

[storage:publicstore]
base_dir = %(data_basedir)s/media/public
base_url = /mgoblin_media/

[celery]
# Put celery stuff here

# Place plugins here, each in their own subsection of [plugins].
# See http://docs.mediagoblin.org/siteadmin/plugins.html for details.
[plugins]
[[mediagoblin.plugins.geolocation]]
[[mediagoblin.plugins.basic_auth]]
[[mediagoblin.plugins.processing_info]]
[[mediagoblin.media_types.image]]
```
